# Generated by Django 4.2.10 on 2026-02-17 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("BA", "Bachelor of Arts"),
                            ("BS", "Bachelor of Science"),
                            ("MA", "Master of Arts"),
                            ("MS", "Master of Science"),
                            ("MBA", "Master of Business Administration"),
                            ("PhD", "Doctor of Philosophy"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("field_of_study", models.CharField(max_length=200)),
                ("graduation_year", models.IntegerField()),
                ("current_company", models.CharField(blank=True, max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("lost_contact", "Lost Contact"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_engagement", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("alumni_summary", "Alumni Summary"),
                            ("partner_summary", "Partner Summary"),
                            ("engagement_analytics", "Engagement Analytics"),
                            ("retention_analysis", "Retention Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("corporate", "Corporate"),
                            ("nonprofit", "Non-profit"),
                            ("government", "Government"),
                            ("educational", "Educational Institution"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("primary_contact_name", models.CharField(blank=True, max_length=100)),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("primary_contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "engagement_level",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                            ("prospective", "Prospective"),
                        ],
                        default="prospective",
                        max_length=20,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("employee_count", models.IntegerField(blank=True, null=True)),
                ("partnership_start_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_engagement", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="core_partne_name_d26c5a_idx"),
                    models.Index(
                        fields=["partner_type"], name="core_partne_partner_4c9cf7_idx"
                    ),
                    models.Index(
                        fields=["engagement_level"],
                        name="core_partne_engagem_6697bf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engagement_type",
                    models.CharField(
                        choices=[
                            ("networking_event", "Networking Event"),
                            ("mentorship", "Mentorship"),
                            ("interview", "Interview"),
                            ("collaboration", "Collaboration"),
                            ("donation", "Donation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("engagement_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="core.alumni",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="core.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["-engagement_date"],
            },
        ),
        migrations.AddIndex(
            model_name="alumni",
            index=models.Index(fields=["email"], name="core_alumni_email_e2fc50_idx"),
        ),
        migrations.AddIndex(
            model_name="alumni",
            index=models.Index(
                fields=["graduation_year"], name="core_alumni_graduat_2992de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alumni",
            index=models.Index(fields=["status"], name="core_alumni_status_a3a8c1_idx"),
        ),
        migrations.AddIndex(
            model_name="engagement",
            index=models.Index(
                fields=["alumni", "engagement_date"],
                name="core_engage_alumni__0adf04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="engagement",
            index=models.Index(
                fields=["partner", "engagement_date"],
                name="core_engage_partner_422220_idx",
            ),
        ),
    ]
