# Generated by Django 4.2.10 on 2026-02-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alumni_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="degree",
            field=models.CharField(
                choices=[
                    ("BS Computer Engineering", "BS Computer Engineering"),
                    ("BS Civil Engineering", "BS Civil Engineering"),
                    (
                        "BS Environmental and Sanitary Engineering",
                        "BS Environmental and Sanitary Engineering",
                    ),
                    ("BS Electrical Engineering", "BS Electrical Engineering"),
                    ("BS Electronics Engineering", "BS Electronics Engineering"),
                    ("BS Mechanical Engineering", "BS Mechanical Engineering"),
                    ("MS Computer Engineering", "MS Computer Engineering"),
                    ("MS Civil Engineering", "MS Civil Engineering"),
                    (
                        "MS Environmental and Sanitary Engineering",
                        "MS Environmental and Sanitary Engineering",
                    ),
                    ("Other", "Other (Specify)"),
                ],
                max_length=120,
            ),
        ),
    ]
