# Generated by Django 4.2.10 on 2026-02-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_alumni_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="degree",
            field=models.CharField(
                choices=[
                    ("BS", "BS"),
                    ("BA", "BA"),
                    ("MS", "MS"),
                    ("MA", "MA"),
                    ("PhD", "PhD"),
                    ("Other", "Other (Specify)"),
                ],
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="engagement_type",
            field=models.CharField(
                choices=[
                    ("networking_event", "Networking Event"),
                    ("mentorship", "Mentorship"),
                    ("interview", "Interview"),
                    ("collaboration", "Collaboration"),
                    ("donation", "Donation"),
                    ("internship", "Internship"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
